import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// import "./globals.css";
import "./handicraftCSS/base.css";
import "./handicraftCSS/responsive.css";
import "./handicraftCSS/grid.css";
import "./handicraftCSS/header.css";
import "./handicraftCSS/footer.css";
import "./handicraftCSS/home.css";
import "./handicraftCSS/iconFontA.css";
// import { ThemeProvider } from "@/components/theme-provider";
import ReduxProvider from "@/redux/provider";

import Header from "./components/partialView/header";
import Footer from "./components/partialView/footer";

const roboto = Roboto({ subsets: ["vietnamese"],weight: ['100','300','400','500','700','900']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{children: React.ReactNode;}>){
  return (
      <html lang="en" suppressHydrationWarning>
        <body className={roboto.className}>
          {/* <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
          > */}
              <ReduxProvider>
                <Header />
                <div className="content">
                    {children}
                </div>
                <Footer />
              </ReduxProvider>
          {/* </ThemeProvider> */}
        </body>
      </html>
  );
}
